INSERT INTO Announcement (ANNOUNCEMENT_NAME,SALARY,JOB,STATUS,ENGLISH) VALUES ('Panasonic Pantalla LCD',20,'JAVA','OPEN','YES');
INSERT INTO Announcement (ANNOUNCEMENT_NAME,SALARY,JOB,STATUS,ENGLISH) VALUES ('Comida marvel',3,'JAVA','CLOSED','NO');
