INSERT INTO Announcements (ANNOUNCEMENT_NAME,SALARY,JOB,STATUS,ENGLISH) VALUES ('Convocatoria para salir de pobre',4000000,'JAVA','OPEN','YES');
INSERT INTO Announcements (ANNOUNCEMENT_NAME,SALARY,JOB,STATUS,ENGLISH) VALUES ('Comida marvel',3,'JAVA','CLOSED','NO');
INSERT INTO Candidates (FIRST_NAME,LAST_NAME,EMAIL,PROGRAMMING_LANGUAGE,ENGLISH,SALARY,SOFT_SKILL) VALUES ('Weiner Eliecer','Molina','weiner@hotmai.com','JAVA','NO','300000','NINGUNA');
INSERT INTO Candidates (FIRST_NAME,LAST_NAME,EMAIL,PROGRAMMING_LANGUAGE,ENGLISH,SALARY,SOFT_SKILL) VALUES ('Jaime Mejia','Quintero','jdmejiaq@unal.edu.co','JAVA','YES','300000','T0DAS');
