INSERT INTO Announcement (ANNOUNCEMENT_NAME,SALARY,END_ANNOUNCEMENT_DATE,INITIAL_ANNOUNCEMENT_DATE,JOB,STATUS) VALUES ('Panasonic Pantalla LCD',20,NOW(),NOW(),'JAVA','OPEN');
INSERT INTO Announcement (ANNOUNCEMENT_NAME,SALARY,END_ANNOUNCEMENT_DATE,INITIAL_ANNOUNCEMENT_DATE,JOB,STATUS) VALUES ('Comida marvel',3,NOW(),NOW(),'JAVA','CLOSED');
